version: "3"
services:
  mysql:
    image: mysql:5.7
    platform: linux/amd64
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: fiber_auth_jwt
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
